### ISSUE TITLE
iOS 16.1

### ISSUE THREAD

**Issue by Andrey5045** [solar2d/demo-app-store-automation#10]
ERROR ITMS-90725: SDK version issue. This app was built with the iOS 15.0 SDK. All iOS and iPadOS apps submitted to the App Store must be built with the iOS 16.1 SDK or later, included in Xcode 14.1 or later.
[2023-06-03 22:03:07 UTC] <main> DBG-X: Returning 1

**Comment by Shchvova** [comment]
this was already fixes. Please update this files:
* [`.github/workflows/list-apple-teams.yml`](https://github.com/solar2d/demo-app-store-automation/blob/master/.github/workflows/list-apple-teams.yml)
* [`.github/workflows/build.yml`](https://github.com/solar2d/demo-app-store-automation/blob/master/.github/workflows/build.yml)
* [`Util/build.sh`](https://github.com/solar2d/demo-app-store-automation/blob/master/Util/build.sh)
* [`Util/deliver.sh`](https://github.com/solar2d/demo-app-store-automation/blob/master/Util/deliver.sh)

**Comment by Andrey5045** [comment]
Thank you!
