### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by alexxbob** [solar2d/demo-app-store-automation#11]
Hi,

After build is done and uploaded to the TestFlight in App Store Connect, there is always a black screen in my IAP shop scene only. 
Black screen blocks UI, but I still can click behind the Black screen on the button (not seeing the button) and test payment works well. 

I tried to disable parts of code to see when black screen appears and it looks like it appears when store.init( transactionListener) happens. 

In transactionListener I also had only simple code for tests

```
local function transactionListener( event )
	local transaction = event.transaction
        if ( transaction.state == "purchased" ) then
       end
end
```

In an old app (last built on 13 mar 2023) I also have the same IAP code and everything works fine. 

In Discord and Forum, I didn’t find any solution.

Tried with build .3697, .3698, .3699

Black screen seen on iOS 17 and 16

Any idea where to dig?

**Comment by Shchvova** [comment]
It is almost certainly some Lua exception is happening. Do you have access to a mac? If you do, you can connect your phone with cable to it, then in Console.app you'll see your phone and you can stream messages from it. It's gonna be a lot. You can filter them by your app process

**Comment by alexxbob** [comment]
> It is almost certainly some Lua exception is happening. Do you have access to a mac? If you do, you can connect your phone with cable to it, then in Console.app you'll see your phone and you can stream messages from it. It's gonna be a lot. You can filter them by your app process

Nope, no mac yet. Tha's why I'm using this App store automation. As i can understand there is no other way to debug this without a mac, right?

**Comment by Shchvova** [comment]
I think you can use https://itools-for-windows.en.softonic.com/ iTools for that.

**Comment by Shchvova** [comment]
Never really done that personally

**Comment by alexxbob** [comment]
Ok, thank you, will try that today

**Comment by alexxbob** [comment]
Borrowed a mac to debug this, iTools didn’t work. I see an error in Console.app on my side indeed. Thank you for the tips and for the fast reply.
