### ISSUE TITLE
SecKeychainItemImport: MAC verification failed

### ISSUE THREAD

**Issue by Be1zebub** [solar2d/demo-app-store-automation#15]
tryin to build demo for ios
```
security: SecKeychainDelete: The specified keychain could not be found.
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
```
![image](https://github.com/user-attachments/assets/4065a831-bda2-45c4-8ddf-516b570a1a08)
![image](https://github.com/user-attachments/assets/0cb054cd-f0aa-4b22-95d6-f005e1a0cc31)

**Comment by Be1zebub** [comment]
at this step `security import "Util/distribution.p12" -A -P "$CERT_PASSWORD"`
![image](https://github.com/user-attachments/assets/c64c21c3-9e16-492d-9557-449e7806764d)
![image](https://github.com/user-attachments/assets/7247d47e-e743-4a81-bc0c-a909dff7a7d4)

**Comment by Shchvova** [comment]
Make sure password is correct in secrets. You can download p12 and try opening it and verifying password. You can also re-generate your keys.

**Comment by Be1zebub** [comment]
confirmed, `$CERT_PASSWORD` 100% correct
<video src="https://github.com/user-attachments/assets/5c6ad637-fe0b-4925-bc97-adbda38a1cea"/>

<img src="https://github.com/user-attachments/assets/3104b209-cb9c-45c1-b8cc-970aea303cf7" width="50%"/>

**Comment by Be1zebub** [comment]
Finnaly solved!
the issue was "the PKCS#12 data uses modern security algorithms that aren’t supported on Apple platforms"

Just added `-legacy` to `x509` & `pkcs12`
on this step
![image](https://github.com/user-attachments/assets/5a6c62b7-5170-47ba-8eef-959eee9897c8)

To confirm, is cert valid for apple platforms: `openssl pkcs12 -in distribution.p12 -info -noout`
it should looks like:
```
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
```
