### ISSUE TITLE
Demo Still Ok?

### ISSUE THREAD

**Issue by corona777** [solar2d/demo-app-store-automation#3]
I'm trying to do a Solar2D Build with no MacOS.  I make it all the way through the instructions but when I click "Run Workflow" the screen refreshes but the workflow never runs (no errors).  Is this demo still good?

Thank you!

**Comment by Shchvova** [comment]
What exact step you are having issues on? If you click "Run Workflow" it is ran. Try to go to Actions tab
<img width="210" alt="image" src="https://user-images.githubusercontent.com/130387/174678576-5ea89f15-5b7c-4764-a226-919600a0b712.png">
And see your run is there.

**Comment by corona777** [comment]
Thank you for looking into this Vlad.  "Actions" tab says "0 workflow runs".  I'm clicking "Run Workflow" under "Build and Deliver".  I'm at the "Building and uploading the App" steps and confirming with the green button.  I look in App Store Connect and it says "No Builds Available".

**Comment by Shchvova** [comment]
This is very weird. You are doing it on your fork, right? I just tried, it all worked for me... Only issue is versions are updated. May be I should make a video tutorial so there's no misunderstandings.

**Comment by corona777** [comment]
Right, I'm doing it on my fork.  Would there be an error message someplace?  Hate to have you go to the trouble of making a video.

**Comment by corona777** [comment]
Something changed.  Now I'm getting a real error:

       actions/checkout@v2 is not allowed to be used in corona777/DadsPrayers. Actions in this workflow must be: within a repository owned by corona777.

I'll troubleshoot...

**Comment by corona777** [comment]
I removed this from build.yml       

     - uses: actions/checkout@v2

and I no longer get the error.  Now I get this:

     line 1: Util/build.sh: No such file or directory

But I can see build.sh in the Util folder. Curious.

**Comment by Shchvova** [comment]
Go to Settings of your repository / Actions / General and make sure "Allow all actions and reusable workflows" is selected. And return `uses: actions/checkout@v2`, because it is what making a copy of the code to work with.

**Comment by corona777** [comment]
Thanks for he guidance Vlad.  That worked.  I'm getting further and now get this error under "Build and Deliver" / "Util/build.sh"

    security: SecKeychainDelete: The specified keychain could not be found.
    security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
