### ISSUE TITLE
Node12 depricated

### ISSUE THREAD

**Issue by Andrey5045** [solar2d/demo-app-store-automation#5]
To be updated with node16.

**Comment by Andrey5045** [comment]
I got no idea what node.js to do with Solar2D, but it is the error message I get when I run "Build and Deliver". Here is an error msg, just in case:

[build](https://github.com/Andrey5045/p247git/actions/runs/3790760165/jobs/6445640940)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by Shchvova** [comment]
Please, edit `.github/workflows/build.yml` changing  `checkout@v2` to `checkout@v3`

**Comment by Andrey5045** [comment]
> 

I should've mentioned that I tried changing "@v2" to "@v3". Error code was still 1, no message about "node.js" version, though...

**Comment by Shchvova** [comment]
So probably your error is something else. You should review logs to know what your error is.

**Comment by Andrey5045** [comment]
Did you check if such a simple change worked on your end and compilation for iOS worked? As for me I got the following msg:

ERROR: with exit code 1 and output: 
error: The specified item could not be found in the keychain.

Node12 did not ask for keychain, node16 does. How to fix it?

**Comment by Shchvova** [comment]
This has nothing to do with the node. Please check which step is failing for you.

**Comment by Shchvova** [comment]
Btw, this should work now, try again
