### ISSUE TITLE
About default parameters for Run Workflow

### ISSUE THREAD

**Issue by AleCGames** [solar2d/demo-app-store-automation#6]
Hi,
I'm pretending using this automation very soon due to I don't have a Mac. I have this question:
After I’ve cloned the repository, could I change the Xcode version parameter (in build.yml) from 13.1 (default release) to the latest release(14.2)?

Thank you in advance

**Comment by Shchvova** [comment]
Absolutely. You also have to bump macOS  version accordingly. I think I'll update the automation today to latest versions.

**Comment by AleCGames** [comment]
Thank you very much Shchvova!
